In [3]:
import pandas as pd
# reads csv file
df = pd.read_csv('players_20.csv')
# set index
df.set_index('short_name', inplace=True)
# select column
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]

# .apply()

In [4]:
import numpy as np
df['age'].apply(np.sqrt)

short_name
L. Messi             5.656854
Cristiano Ronaldo    5.830952
Neymar Jr            5.196152
J. Oblak             5.099020
E. Hazard            5.291503
                       ...
Shao Shuai           4.690416
Xiao Mingjie         4.690416
Zhang Wei            4.358899
Wang Haijian         4.242641
Pan Ximing           5.099020
Name: age, Length: 18278, dtype: float64

In [5]:
def calcu(row):
    return row['age']*8/2
df.apply(calcu,axis=1)

short_name
L. Messi             128.0
Cristiano Ronaldo    136.0
Neymar Jr            108.0
J. Oblak             104.0
E. Hazard            112.0
                     ...
Shao Shuai            88.0
Xiao Mingjie          88.0
Zhang Wei             76.0
Wang Haijian          72.0
Pan Ximing           104.0
Length: 18278, dtype: float64

# LAMBDA

In [10]:
# basic function
def sum_values(a, b):
    x = a + b
    return x
#sum_values(2,3)

sum_values_lambda = lambda a, b: a+b
sum_values(2,3)

5

# .apply()+ LAMBDA

In [14]:
df['age'].apply(lambda x:x*2 )

short_name
L. Messi             64
Cristiano Ronaldo    68
Neymar Jr            54
J. Oblak             52
E. Hazard            56
                     ..
Shao Shuai           44
Xiao Mingjie         44
Zhang Wei            38
Wang Haijian         36
Pan Ximing           52
Name: age, Length: 18278, dtype: int64

In [19]:
df.apply(lambda x: x['weight_kg']/x['height_cm'],axis=1)

short_name
L. Messi             0.423529
Cristiano Ronaldo    0.443850
Neymar Jr            0.388571
J. Oblak             0.462766
E. Hazard            0.422857
                       ...
Shao Shuai           0.424731
Xiao Mingjie         0.372881
Zhang Wei            0.403226
Wang Haijian         0.400000
Pan Ximing           0.428571
Length: 18278, dtype: float64

# .copy()

In [20]:
df_copy=df.copy()

In [21]:
df_copy

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

## deep=True by default (Modifications to the data or indices of the copy will not be reflected in the original object )

In [22]:
# deep=False (Any changes to the data of the original will be reflected in the shallow copy and vice versa)
df_shallow_copy = df.copy(deep=False)
# update value in original dataframe
df.loc['Cristiano Ronaldo', 'height_cm'] = 200
# shallow copy vs original dataframe
df_shallow_copy

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,200,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

## SIMPLE ASSIGNMENT WILL HAVE SAME CHANGES AS THAT OF DF

In [ ]:
# SIMPLE ASSIGNMENT WILL HAVE SAME CHANGES AS THAT OF DF 
df_new_copy = df
# update value in original dataframe
df.loc['Neymar Jr', 'height_cm'] = 190
# copy vs original dataframe
df
df_new_copy